#!/usr/bin/env bash
# Generate code coverage report for src/
set -euo pipefail

source "$(dirname "${BASH_SOURCE[0]}")/_env.sh"

version="${PHP_VERSION}"

docker compose run --rm -e XDEBUG_MODE=coverage "debug${version}" vendor/bin/phpunit --coverage-text --coverage-html=coverage "$@"
