#!/usr/bin/env bash
# Run PHP CS Fixer and apply fixes
set -euo pipefail

source "$(dirname "${BASH_SOURCE[0]}")/_env.sh"

version="${PHP_VERSION}"

docker compose run --rm "php${version}" vendor/bin/php-cs-fixer fix "$@"
