#!/usr/bin/env bash
# Run tests for PHP version set in .env
set -euo pipefail

source "$(dirname "${BASH_SOURCE[0]}")/_env.sh"

version="${PHP_VERSION}"

docker compose run --rm "php${version}" vendor/bin/phpunit "$@"
