<?php

declare(strict_types=1);

namespace Zerotoprod\GitHubSdk\Models;

use Zerotoprod\DataModel\Describe;
use Zerotoprod\GitHubSdk\Internal\DataModel;

/**
 * A resource generated by the task
 * @link https://docs.github.com/
 */
class GetAgentRepoTaskResponseArtifactsItem
{
    use DataModel;

    /** @see $provider */
    public const provider = 'provider';
    #[Describe(['default' => ListAgentRepoTasksResponseTasksItemArtifactsItemProvider::unknown])]
    public ListAgentRepoTasksResponseTasksItemArtifactsItemProvider $provider;

    /** @see $type */
    public const type = 'type';
    #[Describe(['default' => ListAgentRepoTasksResponseTasksItemArtifactsItemType::unknown])]
    public ListAgentRepoTasksResponseTasksItemArtifactsItemType $type;

    /** @see $data */
    public const data = 'data';
    /** @var array<string, mixed> */
    #[Describe(['default' => []])]
    public array $data;
}
